version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-api
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: actividad3
    ports:
      - "3306:3306"